[[dotfile]]
  dest = "~/.compton.conf"
  src = "compton.conf"

[[dotfile]]
  dest = "~/.xmonad/"
  src = "xmonad"

[[dotfile]]
  dest = "~/.tmux.conf"
  src = "tmux.conf"

[[dotfile]]
  dest = "~/.Xmodmap"
  src = "Xmodmap"

[[dotfile]]
  dest = "~/.fehbg"
  src = "fehbg"

[[dotfile]]
  dest = "~/.bashrc"
  src = "bashrc"

[[dotfile]]
  dest = "~/.gitconfig"
  src = "gitconfig"

[[dotfile]]
  dest = "~/.config/fish/"
  src = "config/fish"

[[dotfile]]
  dest = "~/.config/nvim/"
  src = "config/nvim"

[[dotfile]]
  dest = "~/.config/rofi/"
  src = "config/rofi"

[[dotfile]]
  dest = "~/Pictures/danboard.png"
  src = "danboard.png"

[package]
  [package.apt]
    names = [
      "brightd",
      "brightnessctl",
      "compton",
      "curl",
      "docker.io",
      "docker-compose",
      "dunst",
      "feh",
      "fish",
      "git",
      "htop",
      "i3lock",
      "ibus-skk",
      "libbz2-dev",
      "libnotify-bin",
      "libreadline-dev",
      "libsecret-tools",
      "libsqlite3-dev",
      "libssl-dev",
      "isync",
      "make",
      "msmtp",
      "neomutt",
      "neovim",
      "notmuch",
      "peco",
      "rofi",
      "scrot",
      "sl",
      "tmux",
      "w3m",
      "weechat",
      "xmobar",
      "xmonad",
      "xsel",
      "zathura",
    ]
