" vim-tiny or vim-small なら設定を読み込まない
"" if 1 を噛ませることで vi なら内側をコメントとみなす
"" execute 'command': command を実行
"" source hoge: hoge を読み込む
"" expand(): () の中身を展開, shell の変数も展開できる
"" <sfile>: 読み込んだファイル名を展開
"" fnamemodify(a,b): ファイル名 a を b のフォーマットで出力
"" :h: ファイルの親ディレクトリ名を出力
if 1
    execute 'source' fnamemodify(expand('<sfile>'), ':h').'/rc/vimrc'
endif
